[project]
name = "acadsync"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "Flask==3.1.3",
    "Flask-Login==0.6.3",
    "Flask-Migrate==4.1.0",
    "Flask-SQLAlchemy==3.1.1",
    "Flask-WTF==1.3.0",
    "google-generativeai==0.8.6",
    "psycopg2-binary==2.9.12",
    "python-dotenv==1.2.3"
]

[tool.vercel]
entrypoint = "run:app"