"""add weekly progress table

Revision ID: 65c55cefa6ff
Revises: 17d16ff43ace
Create Date: 2026-09-02 23:39:54.321492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c55cefa6ff'
down_revision = '17d16ff43ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Not Started', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'week_number', name='uq_subject_week_number')
    )
    with op.batch_alter_table('weekly_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_progress_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_progress_subject_id'))

    op.drop_table('weekly_progress')
    # ### end Alembic commands ###
