"""add calculation_mode field

Revision ID: 7d9c21f9c945
Revises: ca60474ec142
Create Date: 2026-09-01 12:07:46.416774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9c21f9c945'
down_revision = 'ca60474ec142'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_mode', sa.String(length=20), nullable=False, server_default='raw'))

    with op.batch_alter_table('grade_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_mode', sa.String(length=20), nullable=False, server_default='raw'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('calculation_mode')

    with op.batch_alter_table('grade_templates', schema=None) as batch_op:
        batch_op.drop_column('calculation_mode')

    # ### end Alembic commands ###
