"""add_important_dates_table

Revision ID: c9cc70d47357
Revises: 8801eff7b08c
Create Date: 2026-09-11 01:36:02.320622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cc70d47357'
down_revision = '8801eff7b08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('important_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('important_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_important_dates_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_important_dates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('important_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_important_dates_user_id'))
        batch_op.drop_index(batch_op.f('ix_important_dates_subject_id'))

    op.drop_table('important_dates')
    # ### end Alembic commands ###
