"""add grade templates and assessments

Revision ID: ca60474ec142
Revises: 82f59e0d473b
Create Date: 2026-08-30 15:17:12.311383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca60474ec142'
down_revision = '82f59e0d473b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('university', sa.String(length=10), nullable=False),
    sa.Column('formula_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_templates_user_id'), ['user_id'], unique=False)

    op.create_table('grade_template_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('component_name', sa.String(length=150), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['grade_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_template_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_template_components_template_id'), ['template_id'], unique=False)

    op.create_table('grade_template_grade_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('grade_label', sa.String(length=10), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['grade_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_template_grade_boundaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_template_grade_boundaries_template_id'), ['template_id'], unique=False)

    op.create_table('subject_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('component_name', sa.String(length=150), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_components_subject_id'), ['subject_id'], unique=False)

    op.create_table('subject_grade_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade_label', sa.String(length=10), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_grade_boundaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_grade_boundaries_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('formula_text')

    with op.batch_alter_table('subject_grade_boundaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_grade_boundaries_subject_id'))

    op.drop_table('subject_grade_boundaries')
    with op.batch_alter_table('subject_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_components_subject_id'))

    op.drop_table('subject_components')
    with op.batch_alter_table('grade_template_grade_boundaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_template_grade_boundaries_template_id'))

    op.drop_table('grade_template_grade_boundaries')
    with op.batch_alter_table('grade_template_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_template_components_template_id'))

    op.drop_table('grade_template_components')
    with op.batch_alter_table('grade_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_templates_user_id'))

    op.drop_table('grade_templates')
    # ### end Alembic commands ###
